In [16]:
import pandas as pd
import numpy as np

In [42]:
# file = "example"
file = "input"

df = pd.read_csv(file, sep='\s+', header=None, names=['left', 'right'])

In [43]:
df

      left  right
0    84283  63343
1    35360  98209
2    17841  84541
3    22035  44413
4    43645  22440
..     ...    ...
995  37271  78110
996  59764  98477
997  63559  55088
998  21472  92869
999  70180  11171

[1000 rows x 2 columns]

In [44]:
left = df['left']
right = df['right']

In [45]:
np.sum(np.abs(np.sort(left) - np.sort(right)))

1882714

In [46]:
common_elements = np.intersect1d(left, right)
common_elements

array([15499, 16660, 17588, 25493, 31131, 33787, 35360, 36723, 43676,
       44413, 46651, 47590, 51397, 51736, 58936, 62268, 65775, 71077,
       71149, 72213, 75263, 77212, 78110, 81128, 82666, 83319, 84748,
       86545, 93231, 94756, 96178, 97137, 98209])

In [47]:
left_counts = left.value_counts()
right_counts = right.value_counts()

In [48]:
common_counts = pd.DataFrame({
    'left_count': left_counts[common_elements],
    'right_count': right_counts[common_elements]
})
common_counts['number'] = common_counts.index
common_counts['product'] = common_counts['number'] * common_counts['left_count'] * common_counts['right_count']
common_counts

       left_count  right_count  number  product
15499           1           18   15499   278982
16660           1            7   16660   116620
17588           1            3   17588    52764
25493           1            1   25493    25493
31131           1           10   31131   311310
33787           1            4   33787   135148
35360           1            2   35360    70720
36723           1            5   36723   183615
43676           1           17   43676   742492
44413           1           18   44413   799434
46651           1           11   46651   513161
47590           1            8   47590   380720
51397           1           16   51397   822352
51736           1            1   51736    51736
58936           1           20   58936  1178720
62268           1            4   62268   249072
65775           1           15   65775   986625
71077           1            2   71077   142154
71149           1            6   71149   426894
72213           1            2   72213   144426
75263           1            6   75263   451578
77212           1           12   77212   926544
78110           1           19   78110  1484090
81128           1           13   81128  1054664
82666           1           13   82666  1074658
83319           1           10   83319   833190
84748           1            6   84748   508488
86545           1           18   86545  1557810
93231           1            5   93231   466155
94756           1            9   94756   852804
96178           1           14   96178  1346492
97137           1            8   97137   777096
98209           1            5   98209   491045

In [49]:
common_counts['product'].sum()

19437052